### ISSUE TITLE
Doesn't do anything.

### ISSUE THREAD

**Issue by vraixen** [qx6ghqkz/gallery-dl-server#53]
When i input an url from the web ui or even with a curl it doesn't seems to do anything. (i'm using docker).
Reading the logs it gives me the confirmation 
```
(HTTP redirect to login page (https://www.instagram.com/accounts/login/)
Added url https://x.com/syrup_123/status/1851203226592587795 to the download queue
INFO:     192.168.188.22:5289 - "POST /gallery-dl/q HTTP/1.1" 303 See Other
INFO:     192.168.188.22:5289 - "GET /gallery-dl?added=https://x.com/syrup_123/status/1851203226592587795 HTTP/1.1" 200 OK
INFO:     192.168.188.22:5289 - "GET /icons/apple-touch-icon.png HTTP/1.1" 200 OK
INFO:     192.168.188.22:5291 - "GET /icons/favicon-32x32.png HTTP/1.1" 200 OK)
```

**Comment by vraixen** [comment]
i had to change the target of the out like this:   --mount type=bind,source="/mnt/disk/Downloads",target=/usr/src/app/gallery-dl \ to make it work

**Comment by qx6ghqkz** [comment]
Probably because you didn't specify a user and are running the container as the root user. There's a built in user that has `/usr/src/app` set as the home directory. Add `--user 1000` to your docker run script and `target=/gallery-dl` should work. I should make that more clear.

**Comment by vraixen** [comment]
yeah my bad. i used the user 0 because i'm running this on an LXC of proxmox and by default it uses the root user. 
Btw a bit off topic but would you be interested in adding a box under the url that shows the output/logs. it would make it much easier to figure out whats going on and if it finished to download.

**Comment by qx6ghqkz** [comment]
> would you be interested in adding a box under the url that shows the output/logs

That's a good idea. I'll implement it when I have the time.

**Comment by vraixen** [comment]
> > would you be interested in adding a box under the url that shows the output/logs
> 
> That's a good idea. I'll implement it when I have the time.

I tried doing it by my self, if you want you can give it a look. https://github.com/vraixen/gallery-dl-server
It's not the best because i'm not experienced with html or any web programming languages.
