### ISSUE TITLE
[Feature] View logs from web UI

### ISSUE THREAD

**Issue by qx6ghqkz** [qx6ghqkz/gallery-dl-server#55]
Idea: Add a box which shows the output/logs to the web UI.

Thank you @vraixen for the idea and for your contribution, which is much appreciated.

For now, I have incorporated the changes into the test branch. You can test it out by pulling the image `qx6ghqkz/gallery-dl-server:test`.

It still needs further testing before I incorporate the changes into the main branch. Let me know if there are any issues.

The logs can be viewed directly via the button as well as from the endpoint `/gallery-dl/logs`.

**Comment by vraixen** [comment]
The container logs get flooded with the ""GET /gallery-dl/logs HTTP/1.1" 200 OK" i think that is needed a logic to avoid flooding the logs.

Also i want to point out that the logs that starts with "#" cause a bit of issues, sometimes they do not get catched by the logger. At least we have the exit code that can confirm the completion of the download, although on the gallery-dl repo it's not documented if is reliable or not.

**Comment by qx6ghqkz** [comment]
> The container logs get flooded with the ""GET /gallery-dl/logs HTTP/1.1" 200 OK" i think that is needed a logic to avoid flooding the logs.

That's true. The server logging is handled by Uvicorn. I'll have a look at manually configuring how it logs.

> Also i want to point out that the logs that starts with "#" cause a bit of issues, sometimes they do not get catched by the logger.

That's interesting. I wonder if it has anything to do with comments normally starting with "#" in Python.

The "completed" downloads that start with "#" are files that already exist, by the way, so I don't think it's a major problem. A log message that says "[ERROR] File already exists." would be appropriate for this case.

> The automatic scrolling it's not present so you have to manually scroll down to see the logs.

That's an easy fix. I didn't do too much testing on the live template so I overlooked the automatic scrolling when logs are fetched.

**Comment by qx6ghqkz** [comment]
Okay. The automatic scrolling should be fixed and I disabled Uvicorn's access logging so there will be no more "GET" messages in the container logs.

I'll keep thinking about the "#" issue.

**Comment by vraixen** [comment]
now it makes sense why the "#" appear...

**Comment by qx6ghqkz** [comment]
It should be okay now. It's not perfect, but works as intended. Unless there are any major issues, I'll incorporate the changes into the main branch and continue to work on any further improvements there.

**Comment by qx6ghqkz** [comment]
Closing this issue since the changes have now been implemented. Please open a new issue if there are any further problems or feature requests.
